version: '3'
services:
  backend:
    build:
      context: "./backend/"
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - "db"
  frontend:
    build: "./frontend/"
    ports:
      - "5000:5000"
    depends_on:
      - "backend"
  db:
    build: "./db/"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data:z
volumes:
  pg_data:
