version: '3'
services:
  backend:
    build: 
      context: "./backend/"
    ports:
      - 8080:8080
    depends_on:
      - "redis"
      - "db"
    volumes:
      - ./backend:/cheesecake
  frontend:
    build: "./frontend/"
    ports:
      - "5000:5000"
    depends_on:
      - "backend"
  redis:
    image: "redis:alpine"
  db:
    image: postgres:11.0-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data:z
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheesecake
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
volumes:
  pg_data: