version: '3'
services:
  backend:
    command: "go test -v -cover"
    build: 
      context: "./backend/"
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  frontend:
    command: yarn test
    build: "./frontend/"
    environment:
      ENVIRONMENT: test
  testdb:
    image: postgres:11.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cheesecaketest
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
