FROM golang:1.13
RUN mkdir /cheesecake
WORKDIR /cheesecake
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build
RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]
ENTRYPOINT CompileDaemon -log-prefix=false -build="go build" -command="./backend server"
EXPOSE 8080
