FROM golang:1.13

ADD . /cheesecake

WORKDIR /cheesecake

RUN go get -v ./...

RUN go build

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]

# ENTRYPOINT ["backend", "server"]

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build" -command="./backend server"

EXPOSE 8080
