"""empty message

Revision ID: 431d71b5319b
Revises: 
Create Date: 2019-01-20 22:20:52.085695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '431d71b5319b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('event',
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=25), nullable=True),
    sa.Column('event_code', sa.String(length=10), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.Column('event_type_string', sa.String(length=50), nullable=True),
    sa.Column('first_event_code', sa.String(length=25), nullable=True),
    sa.Column('first_event_id', sa.String(length=50), nullable=True),
    sa.Column('gmaps_place_id', sa.String(length=100), nullable=True),
    sa.Column('gmaps_url', sa.String(length=250), nullable=True),
    sa.Column('key', sa.String(length=25), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('playoff_type', sa.Integer(), nullable=True),
    sa.Column('playoff_type_string', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('short_name', sa.String(length=250), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=True),
    sa.Column('state_prov', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=100), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('team',
    sa.Column('key', sa.String(length=8), nullable=False),
    sa.Column('team_number', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_prov', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('postal_code', sa.String(length=25), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('rookie_year', sa.Integer(), nullable=True),
    sa.Column('motto', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('award',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('award_type', sa.Integer(), nullable=True),
    sa.Column('event_key', sa.String(length=25), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_key'], ['event.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('district_teams',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('district_key', sa.String(length=10), nullable=True),
    sa.Column('team_key', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['district_key'], ['district.key'], ),
    sa.ForeignKeyConstraint(['team_key'], ['team.key'], ),
    sa.PrimaryKeyConstraint('position')
    )
    op.create_table('event_teams',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=10), nullable=True),
    sa.Column('team_key', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['event_key'], ['event.key'], ),
    sa.ForeignKeyConstraint(['team_key'], ['team.key'], ),
    sa.PrimaryKeyConstraint('position')
    )
    op.create_table('match',
    sa.Column('key', sa.String(length=25), nullable=False),
    sa.Column('comp_level', sa.String(length=2), nullable=True),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('winning_alliance', sa.String(length=5), nullable=True),
    sa.Column('event_key', sa.String(length=25), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('actual_time', sa.Integer(), nullable=True),
    sa.Column('predicted_time', sa.Integer(), nullable=True),
    sa.Column('post_result_time', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['event_key'], ['event.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alliance',
    sa.Column('key', sa.String(length=25), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('match_key', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['match_key'], ['match.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('prediction_history',
    sa.Column('key', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match', sa.String(length=25), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['match'], ['match.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alliance_teams',
    sa.Column('position', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alliance_id', sa.String(length=25), nullable=False),
    sa.Column('team_key', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliance.key'], ),
    sa.ForeignKeyConstraint(['team_key'], ['team.key'], ),
    sa.PrimaryKeyConstraint('position', 'alliance_id', 'team_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alliance_teams')
    op.drop_table('prediction_history')
    op.drop_table('alliance')
    op.drop_table('match')
    op.drop_table('event_teams')
    op.drop_table('district_teams')
    op.drop_table('award')
    op.drop_table('team')
    op.drop_table('event')
    op.drop_table('district')
    # ### end Alembic commands ###
