"""empty message

Revision ID: 69e18c572fb7
Revises: 431d71b5319b
Create Date: 2019-03-08 22:04:17.832123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e18c572fb7'
down_revision = '431d71b5319b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_history', 'model',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_history', 'model',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
