FROM postgres:latest
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB cheesecake
ENV POSTGRES_HOST localhost
ENV POSTGRES_PORT 5432
ENV PGDATA /var/lib/postgresql/data/pg_data