FROM postgres:12.2
ENV POSTGRES_USER cheese
ENV POSTGRES_PASSWORD cheesepass4279
ENV POSTGRES_DB cheesecake
ENV POSTGRES_HOST localhost
ENV POSTGRES_PORT 5432
ENV PGDATA /var/lib/postgresql/data/pg_data